"""
Seeds the properties table with realistic DEMO data for the Bangalore
real-estate market. This data is fictional / illustrative and must not be
presented as live, currently-available inventory in the real world.

Run with:  python seed_data.py
"""
from app.database import Base, engine, SessionLocal
from app.models import Property

PROPERTIES = [
    dict(name="Prestige Lakeside Habitat", builder="Prestige Group", location="Whitefield",
         nearby_locations="Varthur, ITPL, Hoodi", property_type="Apartment", bedrooms=3,
         bathrooms=3, area_sqft=1850, price=9_200_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/010120/003201",
         amenities="Clubhouse, Swimming Pool, Gym, Kids Play Area, 24x7 Security, Lake View",
         description="Large lakeside township with landscaped gardens and multiple towers.",
         image_emoji="🏢"),
    dict(name="Brigade Cornerstone Utopia", builder="Brigade Group", location="Whitefield",
         nearby_locations="Varthur, Gunjur", property_type="Apartment", bedrooms=2,
         bathrooms=2, area_sqft=1180, price=6_800_000, possession_date="Dec 2026",
         rera_number="PRM/KA/RERA/1251/446/PR/171020/003512",
         amenities="Clubhouse, Swimming Pool, Jogging Track, Multipurpose Hall",
         description="Large integrated township with retail and office space on-site.",
         image_emoji="🏙️"),
    dict(name="Godrej Air", builder="Godrej Properties", location="Sarjapur",
         nearby_locations="Carmelaram, Bellandur", property_type="Apartment", bedrooms=3,
         bathrooms=3, area_sqft=1650, price=11_500_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/030220/003655",
         amenities="Rooftop Garden, Swimming Pool, Gym, Co-working Lounge",
         description="Mid-rise premium apartments close to the Sarjapur tech corridor.",
         image_emoji="🏢"),
    dict(name="Sobha Dream Acres", builder="Sobha Ltd", location="Bellandur",
         nearby_locations="Panathur, Balagere", property_type="Apartment", bedrooms=2,
         bathrooms=2, area_sqft=1050, price=7_400_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/090120/003310",
         amenities="Clubhouse, Swimming Pool, Tennis Court, Amphitheatre",
         description="Large gated community popular with IT professionals working nearby.",
         image_emoji="🏢"),
    dict(name="Purva Palm Beach", builder="Puravankara", location="Electronic City",
         nearby_locations="Neeladri Nagar, Konappana Agrahara", property_type="Apartment",
         bedrooms=2, bathrooms=2, area_sqft=1020, price=5_600_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/220919/002980",
         amenities="Swimming Pool, Gym, Kids Play Area, 24x7 Security",
         description="Budget-friendly gated community close to Electronic City Phase 1.",
         image_emoji="🏢"),
    dict(name="Shriram Chirping Woods", builder="Shriram Properties", location="Electronic City",
         nearby_locations="Bommasandra, Hosa Road", property_type="Apartment", bedrooms=3,
         bathrooms=2, area_sqft=1450, price=8_100_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/150819/002877",
         amenities="Clubhouse, Swimming Pool, Gym, Landscaped Garden",
         description="Well-established community with mature greenery.",
         image_emoji="🏢"),
    dict(name="Sobha Windsor", builder="Sobha Ltd", location="Koramangala",
         nearby_locations="Ejipura, HSR Layout", property_type="Apartment", bedrooms=3,
         bathrooms=3, area_sqft=1900, price=21_500_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/050718/002310",
         amenities="Clubhouse, Swimming Pool, Gym, Concierge, Covered Parking",
         description="Premium low-rise development in central Koramangala.",
         image_emoji="🏙️"),
    dict(name="Salarpuria Sattva Magnus", builder="Salarpuria Sattva", location="Koramangala",
         nearby_locations="Adugodi, Ejipura", property_type="Apartment", bedrooms=2,
         bathrooms=2, area_sqft=1180, price=15_800_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/120618/002190",
         amenities="Rooftop Pool, Gym, Party Hall, Power Backup",
         description="Central, walkable location near restaurants and offices.",
         image_emoji="🏢"),
    dict(name="Assetz Marq 2.0", builder="Assetz Property Group", location="HSR Layout",
         nearby_locations="Sector 1, Agara", property_type="Apartment", bedrooms=3,
         bathrooms=3, area_sqft=1720, price=14_200_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/280518/002145",
         amenities="Sky Garden, Swimming Pool, Gym, Co-working Space, Amphitheatre",
         description="Design-forward high-rise close to HSR's commercial hub.",
         image_emoji="🏙️"),
    dict(name="Vaswani Autumn", builder="Vaswani Group", location="HSR Layout",
         nearby_locations="Sector 2, Sector 3", property_type="Apartment", bedrooms=2,
         bathrooms=2, area_sqft=1250, price=9_800_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/190418/002088",
         amenities="Clubhouse, Swimming Pool, Gym, Indoor Games",
         description="Mid-size gated community in a quiet residential sector.",
         image_emoji="🏢"),
    dict(name="Prestige Falcon City", builder="Prestige Group", location="JP Nagar",
         nearby_locations="Kanakapura Road, Banashankari", property_type="Apartment",
         bedrooms=2, bathrooms=2, area_sqft=1150, price=8_900_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/091217/001820",
         amenities="Clubhouse, Swimming Pool, Gym, Multiplex Access, Retail Mall",
         description="Large township with retail, entertainment and schools on-site.",
         image_emoji="🏢"),
    dict(name="Adarsh Palm Retreat", builder="Adarsh Developers", location="Bellandur",
         nearby_locations="Outer Ring Road, Kadubeesanahalli", property_type="Villa",
         bedrooms=4, bathrooms=4, area_sqft=3400, price=42_000_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/010816/001420",
         amenities="Private Garden, Clubhouse, Swimming Pool, Golf-Course View, 24x7 Security",
         description="Premium independent villas set within a golf-course community.",
         image_emoji="🏡"),
    dict(name="Provident Botanico", builder="Provident Housing", location="Whitefield",
         nearby_locations="Budigere Cross, Hoskote", property_type="Apartment", bedrooms=2,
         bathrooms=2, area_sqft=980, price=5_900_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/081118/002050",
         amenities="Clubhouse, Swimming Pool, Gym, Kids Play Area",
         description="Affordable, well-connected community on the eastern edge of Whitefield.",
         image_emoji="🏢"),
    dict(name="Century Breeze", builder="Century Real Estate", location="Yelahanka",
         nearby_locations="Jakkur, Thanisandra", property_type="Apartment", bedrooms=3,
         bathrooms=2, area_sqft=1400, price=8_600_000, possession_date="Mar 2027",
         rera_number="PRM/KA/RERA/1251/446/PR/230121/003890",
         amenities="Clubhouse, Swimming Pool, Gym, Jogging Track, Solar Power",
         description="New-launch project in fast-developing north Bangalore.",
         image_emoji="🏙️"),
    dict(name="Brigade Northridge", builder="Brigade Group", location="Yelahanka",
         nearby_locations="Yelahanka New Town", property_type="Apartment", bedrooms=2,
         bathrooms=2, area_sqft=1080, price=6_200_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/141017/001780",
         amenities="Clubhouse, Swimming Pool, Gym, Amphitheatre",
         description="Established community close to the airport and Yelahanka New Town.",
         image_emoji="🏢"),
    dict(name="Embassy Boulevard", builder="Embassy Group", location="Hebbal",
         nearby_locations="Manyata Tech Park, Jakkur", property_type="Apartment", bedrooms=4,
         bathrooms=4, area_sqft=2650, price=31_000_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/050915/001210",
         amenities="Golf-Course View, Clubhouse, Swimming Pool, Spa, Concierge",
         description="Ultra-premium residences adjoining a golf course, near Manyata Tech Park.",
         image_emoji="🏙️"),
    dict(name="RMZ Galleria Residences", builder="RMZ Corp", location="Devanahalli",
         nearby_locations="Bangalore International Airport", property_type="Villa",
         bedrooms=3, bathrooms=3, area_sqft=2200, price=18_500_000, possession_date="Jun 2027",
         rera_number="PRM/KA/RERA/1251/446/PR/010722/004410",
         amenities="Private Garden, Clubhouse, Swimming Pool, Airport Proximity",
         description="Upcoming villa community close to the airport aerotropolis.",
         image_emoji="🏡"),
    dict(name="Sumadhura Silver Ridge", builder="Sumadhura Group", location="Electronic City",
         nearby_locations="Chandapura, Anekal Road", property_type="Apartment", bedrooms=1,
         bathrooms=1, area_sqft=650, price=3_600_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/020618/002102",
         amenities="Gym, Kids Play Area, 24x7 Security",
         description="Compact, budget 1BHK units popular with young professionals.",
         image_emoji="🏢"),
    dict(name="Casagrand Utopia", builder="Casagrand", location="Sarjapur",
         nearby_locations="Wipro Limits, Dommasandra", property_type="Row House", bedrooms=3,
         bathrooms=3, area_sqft=1950, price=13_400_000, possession_date="Sep 2026",
         rera_number="PRM/KA/RERA/1251/446/PR/110321/003760",
         amenities="Private Terrace, Clubhouse, Swimming Pool, Landscaped Streets",
         description="Row houses with private terraces in a low-density layout.",
         image_emoji="🏘️"),
    dict(name="Mahaveer Tuscan", builder="Mahaveer Group", location="JP Nagar",
         nearby_locations="Bannerghatta Road, Sarakki", property_type="Apartment", bedrooms=3,
         bathrooms=3, area_sqft=1580, price=11_900_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/170218/001960",
         amenities="Clubhouse, Swimming Pool, Gym, Rooftop Lounge",
         description="Well-located mid-rise near Bannerghatta Road's retail stretch.",
         image_emoji="🏢"),
    dict(name="Shriram Pristine Willows", builder="Shriram Properties", location="Sarjapur",
         nearby_locations="Attibele Road, Chandapura", property_type="Plot", bedrooms=0,
         bathrooms=0, area_sqft=1200, price=4_200_000, possession_date="Ready to register",
         rera_number="PRM/KA/RERA/1251/446/PR/220520/003450",
         amenities="Gated Layout, Underground Wiring, Avenue Plantation, Clubhouse",
         description="Plotted development for those who want to self-build.",
         image_emoji="🏞️"),
    dict(name="Provident Sunworth City", builder="Provident Housing", location="Electronic City",
         nearby_locations="Bommasandra Industrial Area", property_type="Apartment", bedrooms=2,
         bathrooms=2, area_sqft=1000, price=5_400_000, possession_date="Ready to move",
         rera_number="PRM/KA/RERA/1251/446/PR/090319/002620",
         amenities="Clubhouse, Swimming Pool, Gym, Kids Play Area",
         description="Large affordable-housing community near Electronic City Phase 2.",
         image_emoji="🏢"),
]

for p in PROPERTIES:
    p["price_per_sqft"] = round(p["price"] / p["area_sqft"], 2)


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing = db.query(Property).count()
        if existing > 0:
            print(f"Properties table already has {existing} rows — skipping seed. "
                  f"Delete rows first if you want to reseed.")
            return
        for data in PROPERTIES:
            db.add(Property(**data))
        db.commit()
        print(f"Seeded {len(PROPERTIES)} demo properties.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
